### ISSUE TITLE
Add support for modules

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#104]
Race against the clock! This depends on when 1.3 comes out (supposed to ship w/ native import support). If we get to this before 1.3, we can use [this package](https://github.com/vazco/universe-modules).

**Comment by jamiedumont** [comment]
Have you experimented with any of the 1.3 beta releases, or are you waiting for the final release( due of I Feb. I believe)?

**Comment by themeteorchef** [comment]
Not yet. I do plan on updating but need to find some time to explore the new stuff and do conversions.
