### ISSUE TITLE
Use React-Bootstrap

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#105]
Would like to make use of [React-Bootstrap](https://react-bootstrap.github.io/) once it's stable/passes 1.0.0. For now, just use custom parts (there isn't much by default).

**Comment by Giantwannabe** [comment]
:+1:  Awesome!

**Comment by themeteorchef** [comment]
On second pass this is more-or-less usable for now. Once we get Blaze 4.0.0 out, use that as our starting point and refactor using React. A bit of work but would rather this is based on a maintained release of Bootstrap instead of my own frankenstein thingamajig.

**Comment by zeroasterisk** [comment]
fyi - I've been very happy with reactstrap, if you're ready to go bootstrap4
https://github.com/reactstrap/reactstrap

**Comment by themeteorchef** [comment]
@zeroasterisk I'll take a peek, thank you for sharing! Not against using bootstrap4 at all.

**Comment by zeroasterisk** [comment]
Cool - also - might be outside of the scope of this project, but I'm toying with releasing a few React Components wrapped with Meteor... I've got a very nice Autocomplete --> Multiselect wiget
