### ISSUE TITLE
Is there a better way to do validation for components?

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#106]
Right now the consensus on this is low. There doesn't seem to be a "this" style of answer to the question of how to handle form validation in React. Right now, jQuery Validation works well (no noticeable issues), but the organization of it begs for something better. 

Rolling something custom is _not_ preferred unless it's absolutely necessary. I haven't investigated how well you can style HTML5 validation with CSS, but if this is possible/consistent across browsers, I'm all for it. 

As a side note: I want to avoid getting tangled up in other libraries like [Formsy](https://github.com/christianalfoni/formsy-react). As closes as possible to raw forms is preferred, no magic/coupling.

P.S. This is an open question for myself and others who have experience.

**Comment by stocksp** [comment]
As you are using react-bootstrap do you see an issue with [react-bootstrap-validation](https://github.com/heilhead/react-bootstrap-validation) ?

**Comment by themeteorchef** [comment]
Hey, @stocksp thanks for sharing this :)

My hesitations here are:

- Support/usage. The goal here is to avoid the need to swap out parts again later (or too frequently) if a project goes flat. There's [an issue](https://github.com/heilhead/react-bootstrap-validation/issues/43) about finding a maintainer that makes me a bit cautious.
- Coupling. Because this wraps the Bootstrap React components, it requires another layer of abstraction. This isn't too big of a deal, but because of the item above I'd like to know it's supported long-term.

I'll keep an eye on this project! It seems like it may be a good fit once it gets some support behind it.

**Comment by philippeluickx** [comment]
Does this link to https://github.com/themeteorchef/base/issues/99 ? I am not a big fan of the bootstrap validation, because this would tie in the bootstrap front-end more. At the moment it is nice to be able to replace the bootstrap library with something else, but if it is coupled with validation, you actually do lose functionality.
