### ISSUE TITLE
Seeder causes app crash on startup

### ISSUE THREAD

**Issue by StonJarks** [themeteorchef/base#116]
Hey Ryan,

I was trying your new recipe and cloned the 4.0.0 version of base:
`git clone -b 4.0.0 https://github.com/themeteorchef/base.git`

When running npm start the app crashes with following error from the server:

`Type error: object is not a function at _seedUsers (server/modules/seed-database.js:4:3) at exports.default (server/modules/seed-database.js:18:3)`
 ....

I didn't touch the code so far.

`meteor --version: Meteor 1.3-beta.12` on Windows 7.

themeteorchef:seeder is installed in packages

Any thoughts what went wrong?

Thanks

**Comment by themeteorchef** [comment]
Hmm, not entirely. To confirm, this boots up okay if you uninstall the package?

**Comment by StonJarks** [comment]
Yap. I switched seeder with the generateAccount / faker method from master an it builds and boots.
Tested on OSX.

**Comment by themeteorchef** [comment]
Okay, got it. I'll take a peek at the seeder package and see what's up. Should have known better than to release that in a beta state :p

**Comment by ChristBKK** [comment]
same problem :)

**Comment by StonJarks** [comment]
@ChristBKK This is not a solution, as the problem seems to be in the Seeder package, but a workaround:
1) 
```
meteor remove themeteorchef:seeder
meteor add digilord:faker
```

2)
replace the content of server/seed-database.js with this:
```
let administrators = [
  {
    name: { first: 'Admin', last: 'McAdmin' },
    email: 'admin@admin.com',
    password: 'password'
  }
];

let seedUsers = () => {
  let fakeUserCount = 5,
      usersExist    = _checkIfAccountsExist( administrators.length + fakeUserCount );

  if ( !usersExist ) {
    _createUsers( administrators );
    _createUsers( _generateFakeUsers( fakeUserCount ) );
  }
};

let _checkIfAccountsExist = ( count ) => {
  let userCount = Meteor.users.find().count();
  return userCount < count ? false : true;
};

let _createUsers = ( users ) => {
  for ( let i = 0; i < users.length; i++ ) {
    let user       = users[ i ],
        userExists = _checkIfUserExists( user.email );

    if ( !userExists ) {
      _createUser( user );
    }
  }
};

let _checkIfUserExists = ( email ) => {
  return Meteor.users.findOne( { 'emails.address': email } );
};

let _createUser = ( user ) => {
  Accounts.createUser({
    email: user.email,
    password: user.password,
    profile: {
      name: user.name
    }
  });
};

let _generateFakeUsers = ( count ) => {
  let users = [];

  for ( let i = 0; i < count; i++ ) {
    users.push({
      name: { first: faker.name.firstName(), last: faker.name.lastName() },
      email: faker.internet.email(),
      password: 'password'
    });
  }

  return users;
};

export default function() {
  seedUsers();
}
```

Now you should be able to startup and seed the database.

**Comment by ChristBKK** [comment]
Thank you my friend! Great help

**Comment by Nanyte25** [comment]
this solved the issue for me aswell.
