### ISSUE TITLE
Switch to React by default

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#117]
It's becoming clear that React is the preferred UI layer and more efforts are moving in that direction. In order to keep our teaching up with the latest standards, it's looking like React should be the _default_ over Blaze. The convention would need to then be:

- `master` = React
- `base-blaze` = Blaze
- `base-others` = Other frameworks

Existing 4.0.0 work should be moved to a `base-blaze` branch.

**Comment by jamiedumont** [comment]
I support this wholeheartedly!

**Comment by discdiver** [comment]
Agree!

Have a great day,
Jeff
