### ISSUE TITLE
Check for logged in user before do form validation

### ISSUE THREAD

**Issue by meshekhar** [themeteorchef/base#119]
I need only logged-in users to add comments on a blog page. The commenting template is open to public and only when the add comment button is pressed there should be a check for logged in user. If not logged in then I like to show a custom alert on a div  above button or a simple Bert alert. 

How do I or where do I add a check for logged in user (Meteor.UserId()) before do the form validation with jQuery.

**Comment by meshekhar** [comment]
I found the following works for me:

submitHandler() {
      if(Meteor.userId()){
        _handleNewQComment(template, postId);
      }else{
        console.log("Not signed in");
      }
    }

**Comment by themeteorchef** [comment]
Good to see you figured this out :)
