### ISSUE TITLE
How to redirect to requested page after login?

### ISSUE THREAD

**Issue by meshekhar** [themeteorchef/base#123]
Scenario: Lets say a user try to access a new blog post page which can only be accessible by logged in users so meteor app sends user to the login page then after successful login user should be redirect back to the new post page.

Currently after accessing a authenticated route it redirects to "/".

```
redirectAuthenticated() {
	 	return handleRedirect([
			'**login**',
			'signup',
			'recover-password',
			'reset-password'
		], '/' );
	},
```

Please help.

**Comment by resmith** [comment]
My recommendation would be to pass a parameter specifying the page they should be directed to after logging in. For example ?redirectAfter=newBlogPost. Then the login needs to check for that parameter and redirect them to if afterwards.

**Comment by meshekhar** [comment]
I will try suggested approach.  Can this be added as a feature?

**Comment by themeteorchef** [comment]
@meshekhar take a peek at the source updated yesterday. Base now uses React Router which has this baked in by default (take a peek at the login flow to see how this is working). Going to close this out but feel free to append questions in here :)
