### ISSUE TITLE
Use Imports for everything possible

### ISSUE THREAD

**Issue by patrickml** [themeteorchef/base#124]
With the new 1.3 syntax we can use the import system for pretty much everything. The MDG has shown that you can import meteor like so `import { Meteor } from 'meteor/meteor';` and import packages like so `import { Roles } from 'meteor/alanning:roles';`. I am assuming that one of the reasons for this is because one day meteor will be moving from atmosphere and are currently working on moving away from the use of globals. Adding these imports shouldn't hurt anything and will only prevent headaches in the future. Additionally, it will help with the readability of code by stating where an object is coming from.

I am proposing that Base 4.X should take this route as well. I am curious to hear other individuals input on this subject.

**Comment by themeteorchef** [comment]
Down for this! Is there a way to test this? It seems like you could implement an import but if the global exists not really know if it's taking...

**Comment by patrickml** [comment]
Yup you could check if it's undefined. Some packages don't export variables
they append them to window so packages like that cannot be imported

**Comment by zeroasterisk** [comment]
Agree - this is a great proposal...

**Comment by themeteorchef** [comment]
> Yup you could check if it's undefined. Some packages don't export variables
they append them to window so packages like that cannot be imported

👍  sound good to me, flagging this as a refactor!

**Comment by sinchi** [comment]
Hello 
I want know please what does this declaration means in the Base v4 

const { location } = component.props 

especially this declaration is JS [ const { location } ] ?

thank you

**Comment by josephdburdick** [comment]
@sinchi check out the new standard JS syntax from ES2015, this is known as "destructuring". Looks funky at first but I promise it'll make sense really quick and you once you get it you'll love it and use it all the time.
Check it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by sinchi** [comment]
@josephdburdick  thank you very much
