### ISSUE TITLE
requireAuth with Meteor.user() 

### ISSUE THREAD

**Issue by LTict** [themeteorchef/base#126]
From previous posts, and also some testing I noticed that Meteor.user() is "slow" loading function. It fetches all user data and only returns it when it fetched all data. This could result in a redirect while you are logged in, and want to acces a specific page. 
If you use Meteor.userId() you get a near instant reactive function of Meteor.  

Could you explain the decision for using Meteor.user() in React Router? 

And what if you need more specific authentication, like using Meteor.user().profile.emails[0].verified: true, else redirect to "/verify-email"? 

Would love to hear from you,
Lars

**Comment by zeroasterisk** [comment]
Agreed, I'd like to see `requireAuth` not rely on Meteor at all, but instead rely on props passed down from parent or perhaps redux...  It seems like once you get into `imports/ui/...` unless you're in a container, it should not have any Meteor plumbing...

https://github.com/themeteorchef/base/blob/master/imports/startup/client/routes.js#L14-21

_(BTW - thanks 1,000,000 for this repo and project.  It's super useful.)_

**Comment by themeteorchef** [comment]
The decision for `Meteor.user()` was to control routing based on the Meteor accounts system. There's no marriage to `Meteor.user()`. Happy to switch to `Meteor.userId()` to get the performance bump.

Re: specific authentication, this should be doable in the `requireAuth` method. Have you implemented this and it's _not_ working?

@zeroasterisk May need some help here as my Redux knowledge is...zilch. I'd disagree that there should be no Meteor plumbing as the goal here is to tap into the Meteor accounts system to control routing. If you have a pattern in mind for working around this I'm more than open to proposals!
