### ISSUE TITLE
Example of an async complex routes setup

### ISSUE THREAD

**Issue by zeroasterisk** [themeteorchef/base#127]
Can you provide an example of how you'd implement a large app routes setup?

Assume I have several sets of multiple nested routes (perhaps in modules _{mantra}_, perhaps just split up in imports _{meteor guide}_)... I've seen that `ReactRouter` supports async route injection, but I know quite know how to wire it in... Any chance you could either update your base router, or create a variation which does this?  I think it's a very useful piece of information, both for code organization and performance.

**Comment by themeteorchef** [comment]
I haven't used this in an app with any _crazy_ number of routes yet, but here's a slightly expanded version of what's here in Base:

```javascript
Meteor.startup(() => {
  render(
    <Router history={ browserHistory }>
      <Route path="/" component={ App }>
        <Route name="login" path="/login" component={ Login } />
        <Route name="recover-password" path="/recover-password" component={ RecoverPassword } />
        <Route name="reset-password" path="/reset-password/:token" component={ ResetPassword } />
        <Route name="signup" path="/signup" component={ Signup } />
        <Route path="/projects">
          <IndexRoute name="projects" component={ Projects } />
          <Route name="viewProject" path="/:name">
            <Route path="/issues" onEnter={ requireAuth }>
              <IndexRoute name="issues" component={ Issues } />
              <Route name="newIssue" path="/new" component={ NewIssue } />
              <Route name="issue" path="/:number" component={ Issue } />
            </Route>
            <Route name="labels" path="/labels" component={ Labels } />
            <Route path="/milestones">
              <IndexRoute name="milestones" component={ Milestones } />
              <Route name="newMilestone" path="/new" component={ Milestone } />
              <Route name="editMilestone" path="/:_id/edit" component={ Milestone } />
            </Route>
          </Route>
        </Route>
        <Route path="*" component={ NotFound } />
      </Route>
    </Router>,
    document.getElementById('react-root')
  );
});
```

Re: async route injection, I'm not sure what this is. Can you link me up to some more info on this? May be able to advise once I see it.

**Comment by zeroasterisk** [comment]
Thanks.  Take a look at this: https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md

Specifically:

> React Router does all of its path matching and component fetching asynchronously, which allows you to not only load up the components lazily, but also lazily load the route configuration. You really only need one route definition in your initial bundle, the router can resolve the rest on demand.
>
> Routes may define getChildRoutes, getIndexRoute, and getComponents methods. These are asynchronous and only called when needed. We call it "gradual matching". React Router will gradually match the URL and fetch only the amount of route configuration and components it needs to match the URL and render.

I don't know if that really gains us anything at all with meteor as our builder vs. webpack... thoughts?

**Comment by themeteorchef** [comment]
> I don't know if that really gains us anything at all with meteor as our builder vs. webpack... thoughts?

For something like Base, I'd say no. This is neat for something at a bigger scale but as the focus here is simplicity first something like this would be overkill. Perhaps a tutorial would be good at some point :)
