### ISSUE TITLE
Match latest React Boostrap API

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#129]
Well, potatoes. Looks like the React Bootstrap camp has changed out the form APIs a bit. Only one I'm catching now is that `<Input />` has been deprecated in favor of `<FormControl />`. Should check for other breaking changes [here](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md).

**Comment by redwards1966** [comment]
I found the same thing after I updated to the latest version. For instance in register the firstName field now looks like this:

          <FormGroup controlId="firstName">
            <ControlLabel>First Name</ControlLabel>
            <FormControl
              type="text"
              name="firstName"
              placeholder="First Name"
            />
          </FormGroup>

**Comment by redwards1966** [comment]
Also noticed, I'm now getting 'login.js:9 Uncaught TypeError: Cannot read property 'value' of undefined' so it looks like the change to FormGroup et al is causing some issues getting the values on submit.

**Comment by themeteorchef** [comment]
Hey @redwards1966! Yes, this is a gotcha I've been trying to figure out as well. Something about the new structure of the `<FormControl />` component is making the value inaccessible via refs (the current pattern). I need to sit down and play with it again. If you figure something out let me know otherwise watch the repo for updates.

**Comment by themeteorchef** [comment]
@redwards1966 just a heads up, found a fix for this and it's now live! The solution involved using `ReactDOM.findDOMNode(component.refs.someRefName).value` to get the appropriate value.

**Comment by redwards1966** [comment]
@themeteorchef Thanks for the update. I've integrated the changes into my repo and it's working great.
