### ISSUE TITLE
Error Getting Started Meteor Base V4.0 Node Fibers is Missing

### ISSUE THREAD

**Issue by rijdz** [themeteorchef/base#130]
I have successfully do command npm install. But when I try to do meteor command or npm start the command prompt throw error installing in node fibers.
Try to uninstall then re-install node fibers. Still error.

I'm using node version v5.1.0. Do I have to downgrade the version of node that I'm using for this base version?

**Comment by themeteorchef** [comment]
Are you on Windows or OSX? I've seen quite a few issues on the Windows side lately around an error with Fibers.

**Comment by arthurkirsz** [comment]
@rijdz I solved this problem by downgrading node to version 0.10.4 which apparently is the only version Meteor supports at the moment. 

However, when you reinstall node, you get an old version of npm which might not work when you `npm install` on base V4. 

If so, make sure to reinstall node v0.10.4 and then update your npm to the latest version. Hope this solves you problem :)

**Comment by themeteorchef** [comment]
Going to close this out for now but if this fix doesn't work feel free to repopen/keep chatting in here.

**Comment by rijdz** [comment]
@arthurkirsz I've tried with 0.10.40,0.10.41, 0.10.33 and updating the npm as your suggestion, but seems like nothing worked.
I'm using windows7 32 bit by the way.

Recently an MDG developer successfully build the meteor app using node version 5.x.x
https://github.com/meteor/meteor/issues/5124#issuecomment-210174338
But somehow it didn't work for my environment with the same node version.

**Comment by arthurkirsz** [comment]
@rijdz I'm using windows7 64. I have 0.10.4 installed. Did you uninstalled node correctly ? I did have a hard time to delete everything and reinstall a clean node. 

(Make sur to close your cmd after the reinstall, sounds stupid but some collegues did it, so...)

**Comment by lukeadams** [comment]
@rijdz While the Meteor Team is working on upgrading to the latest node version, it's not there yet. It's too early to open issues on non-meteor projects as the bug is probably in meteor-core and not here.

**Comment by robdonn** [comment]
Hey, I ran into this issue this morning and figured out how to get it working without needing to downgrade npm.

I first made sure I had node-gyp installed and had Visual C++ Build Tools and Python 2.7 installed.

Then after cloning Base, instead of running `npm install` I ran `meteor npm install`.

Fibers built correctly and everything works great now - Windows 10 x64
