### ISSUE TITLE
CPU utilization over 100% when using npm start

### ISSUE THREAD

**Issue by sergeant-q** [themeteorchef/base#136]
CPU is maxing out at 174% when using the `npm start` command as opposed to the standard `meteor --settings settings-development.json` command.

`node --version = 4.4.3`
`npm --version  = 2.15.1`
`OS: Mac OS X 10.11.14`

**Comment by sergeant-q** [comment]
I was able to reference this issue https://github.com/meteor/meteor/issues/4314  and the fix is if you want to run an npm script you must run it as `meteor npm start` in this example.

**Comment by themeteorchef** [comment]
[Docs](https://themeteorchef.com/base/npm-scripts/) have been updated to reflect this.
