### ISSUE TITLE
Base installation fail

### ISSUE THREAD

**Issue by notgoodwithpowertools** [themeteorchef/base#140]
Ubuntu 16.04
Meteor 1.3.2.4

As per installation instructions, run npm install

npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
extract:oauth-sign → gunz ▐ ╢████████████████████████████████████░░░░░░░░░░░░░╟
Killed

... any ideas??

**Comment by AAZZIOUI** [comment]
I have the same OS, same Meteor version and had some similar issues too. Now it works fine.
I went back to the history of my commands in the Terminal, and found out that after this first failure, all what I have done is the following ( first make sure you're in base directory ):
 1: npm update
 2: meteor update
 3: meteor update dburles:factory (I think this one could be skipped, but I've done it)
 4: meteor  => it worked now just fine.

Hope this helps.

**Comment by notgoodwithpowertools** [comment]
Thanks so much for the response. To get around this:
- meteor update
- sudo npm update

* Make sure to use sudo for privileged access to node files.

While there are still some warnings Base does start OK.

Warnings/Errors still present include:

UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^0.6.2

lodash.memoize@4.0.3
npm ERR! peer dep missing: eslint-plugin-jsx-a11y@^0.6.2, required by eslint-config-airbnb@7.0.0

**Comment by DevanB** [comment]
> UNMETPEER DEPENDENCY eslint-plugin-jsx-a11y@^0.6.2

@notgoodwithpowertools NPM 3+ does not automatically install peerDependencies. Because of this, `eslint-plugin-jsx-a11y` was not installed. To fix this you only need to install `eslint-plugin-jsx-a11y`.

**Comment by notgoodwithpowertools** [comment]
Thanks for the response. Sorry to be vague but tried the npm install eslint-plugin-jsx-a11y --save
... but it didn't seem to install leaving the following warning...

npm WARN eslint-config-airbnb@7.0.0 requires a peer of eslint-plugin-jsx-a11y@^0.6.2 but none was installed.

Should I worry about this?

**Comment by themeteorchef** [comment]
@notgoodwithpowertools this should be corrected in Base 4.2.0.
