### ISSUE TITLE
Dropping Base into Webpack kickstart

### ISSUE THREAD

**Issue by josephdburdick** [themeteorchef/base#141]
I've been working with v4 for a bit and it's great. At work I've been working in React for a while and v4 is very refreshing. The only issue I have is that the Meteor builder is seems pretty slow and after seeing how fast Webpack is I was wondering if I could drop Base into [The Reactive Stack's Meteor Webpack kickstart](https://github.com/thereactivestack/kickstart-meteor-react-router). So, it's been over a day of tinkering, all the errors are gone, all dependencies are properly in place, but the client just shows up blank. 🚪 

I've created an issue on the kickstart's repo as well, and [it can be found here](https://github.com/thereactivestack/kickstart-meteor-react-router/issues/80) I just wanted to also send you a message if you had any ideas. Theoretically it _should_ work– both use Meteor 1.3+, NPM + Meteor packages, imports, React, React Router is different but their version is based on React Router. Any thoughts?  Thanks so much!

**Comment by josephdburdick** [comment]
To follow up, I think that there's a debate going on about Webpack in Meteor or not, and that there are legitimate reasons why MDG will probably not adopt Webpack in the build system. That said, this appears to be on their radar: Hot Module Replacement (https://github.com/gadicc/meteor-hmr). If I could do anything to improve the development process it would be to speed up the client refresh.  Anyway, I just wanted to add possibly insightful information to this issue.

**Comment by themeteorchef** [comment]
Hey @josephdburdick thanks for this :) I'd definitely leave something like this to Meteor core as opposed to baking it into Base.
