### ISSUE TITLE
Window.confirm() should be replaced with a styled solution

### ISSUE THREAD

**Issue by mbrookes** [themeteorchef/base#147]
https://github.com/themeteorchef/base/blob/master/imports/ui/components/document.js#L24

**Comment by themeteorchef** [comment]
Thanks for adding this @mbrookes :)

**Comment by mbrookes** [comment]
I did more than that: #148 :)

**Comment by themeteorchef** [comment]
Going to close this out for now as I'd like to add support for confirms in an upcoming release of Bert. Thank you for contributing the PR :)

**Comment by mbrookes** [comment]
Doesn't look like that ever happened. I appreciate you don't need the PR, but not sure why this issue was closed, as it's still unresolved.

**Comment by themeteorchef** [comment]
@mbrookes not yet, but the refactor of Bert is under way and should be released in the coming weeks. I'll pop this back open as you're right, it's specific to Base.

**Comment by mbrookes** [comment]
> "should be released in the coming weeks"

How's it coming along?

**Comment by arthurkirsz** [comment]
Would love a refactor / improvement of Bert !
Le sam. 11 nov. 2017 à 01:54, Matt Brookes <notifications@github.com> a
écrit :

**Comment by cleverbeagle** [comment]
@mbrookes Bert is unfortunately hospitalized and in a coma at the moment following a freak accident involving Bert being mistaken for a prop in the killer whale extravaganza at Sea World.

Doctors are hopeful, though, as he's been starting to show signs of movement.

**Comment by mbrookes** [comment]
Closing this, since base appears to be abandonware, and Meteor is falling out of favour.

**Comment by themeteorchef** [comment]
@mbrookes holy FUD, Batman. Base is not abandonware. It was deprecated in favor of its successor, [Pup](https://cleverbeagle.com/pup).
