### ISSUE TITLE
Add allow/deny rules to documents collection

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#149]
It looks like these were omitted during the move from 1.2 to 1.3. Need to update so that the `Documents` collection is locked down on the client by default.

**Comment by arthurkirsz** [comment]
Seems to me that we shouldn't lock by default the documents :(

Le jeu. 9 juin 2016 18:11, The Meteor Chef <notifications@github.com> a
écrit :

**Comment by rglover** [comment]
@arthurkirsz why's that? It's generally recommended to use method-only database operations (and avoid the client). Any details on why you'd go against this?

See [this](http://guide.meteor.com/methods.html#comparison-with-allow-deny) in the Meteor Guide.
