### ISSUE TITLE
Heroku slug size

### ISSUE THREAD

**Issue by ahaghdan** [themeteorchef/base#150]
Hi,

I have an issue with base, when adding spiderable to improve SEO, I get slug size too big when uploading/building to heroku. Heroku has a few support chapters about this but I am not sure that will resolve this problem. Does anyone have experience and workaround for me?

Thanks,

**Comment by themeteorchef** [comment]
Hmm not sure, sorry. Going to close this out as it doesn't sound like an issue with Base but with Spiderable. I'm going to close this but feel free to add notes/chat in here :)

**Comment by ahaghdan** [comment]
Ok, the slug size is 250 MB from beginning without any addons like spiderable. Heroku offers free account, it would be great if you could test this for me/us and offer a workaround/solution. So if I add a little content it will walk over 300 MB and then refuse to push to Heroku.
