### ISSUE TITLE
Master branch has build failed error on github

### ISSUE THREAD

**Issue by AnnotatedJS** [themeteorchef/base#153]
Master branch has build failed error on github

![branches themeteorchef-base 2016-06-19 11-32-46](https://cloud.githubusercontent.com/assets/11474975/16176472/f32d3936-3610-11e6-931e-5b837ccc00ea.png)

**Comment by themeteorchef** [comment]
@AnnotatedJS are you using a specific plugin for this (not sure how to see this view in GitHub)? I'm not using any CI stuff at the moment, either, so not sure where this would be popping up.

**Comment by AnnotatedJS** [comment]
On the GiHub Base page you can click on the [branches link](https://github.com/themeteorchef/base/branches) which will take You a page with the (currently) 6 branches. There you can see, conform above picture, that the master branch has a red cross. If you hoover above it, you will see the "Error: Build failed" warning.

I don know what this means and how GitHub came to this conclusion about the master branch.
