### ISSUE TITLE
Guidance on using material-ui

### ISSUE THREAD

**Issue by acomito** [themeteorchef/base#159]
Great start kit.

I was thinking about forking base and creating a material-ui version. Anything in particular I should be looking out for before I embark on this journey?

**Comment by themeteorchef** [comment]
Thanks :) Nothing much if you're just swapping out UI. May be worth reviewing how the various methods are called before you start swapping components.

**Comment by acomito** [comment]
initial commit!

https://github.com/acomito/base-material-ui

So far so good as most of the work was done in base...just needed a little swapping and swiping. Still some work to do. Suggestions/feedback/PRs/etc. etc. etc. always welcome.
