### ISSUE TITLE
Not working Windows 10

### ISSUE THREAD

**Issue by sonicviz** [themeteorchef/base#160]
I've just done a complete uninstall/reinstall of Meteor on Win 10, tested on a few apps and all seems fine.

Tried the latest base 4.4 and after npm install, then a loooong time updating and installing packages it fails:

G:\Meteor Projects\Meteor 1.3\MeteorChef\Base4.4>meteor
[[[[[ ~\G\Meteor Projects\Meteor 1.3\MeteorChef\Base4.4 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Meteor 1.3.4.4 is available. Update this project with 'meteor update'.
W20160715-11:34:54.235(9)? (STDERR)
W20160715-11:34:54.395(9)? (STDERR) G:\Meteor Projects\Meteor 1.3\MeteorChef\Base4.4\node_modules\fibers\fibers.js:16
W20160715-11:34:54.400(9)? (STDERR)     throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
W20160715-11:34:54.404(9)? (STDERR)           ^
W20160715-11:34:54.406(9)? (STDERR) Error: `G:\Meteor Projects\Meteor 1.3\MeteorChef\Base4.4\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node` is missing. Try reinstalling `node-fibers`?
W20160715-11:34:54.412(9)? (STDERR)     at Object.<anonymous> (G:\Meteor Projects\Meteor 1.3\MeteorChef\Base4.4\node_modules\fibers\fibers.js:16:8)
W20160715-11:34:54.417(9)? (STDERR)     at Module._compile (module.js:456:26)
W20160715-11:34:54.420(9)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160715-11:34:54.425(9)? (STDERR)     at Module.load (module.js:356:32)
W20160715-11:34:54.428(9)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160715-11:34:54.431(9)? (STDERR)     at Module.require (module.js:364:17)
W20160715-11:34:54.434(9)? (STDERR)     at require (module.js:380:17)
W20160715-11:34:54.437(9)? (STDERR)     at Object.<anonymous> (G:\Meteor Projects\Meteor 1.3\MeteorChef\Base4.4\.meteor\local\build\programs\server\boot.js:1:75)
W20160715-11:34:54.444(9)? (STDERR)     at Module._compile (module.js:456:26)
W20160715-11:34:54.447(9)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
=> Exited with code: 8
Terminate batch job (Y/N)?

**Comment by notsofun** [comment]
Same issue with 4.5.0.  Only dependency that's not installed is 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8

I don't think this should affect the overall build though.

**Comment by themeteorchef** [comment]
Hm, this isn't a direct dependency of Base (it looks like a peer dependency of something else). Is that the only error you get @notsofun?

**Comment by notsofun** [comment]
@themeteorchef Yeah the only one.

**Comment by themeteorchef** [comment]
Okay. I need to check dependencies in relation to something else so I'll see if I can figure out what's up here :)

**Comment by themeteorchef** [comment]
Going to close this for now. It seems unrelated to Base directly.

**Comment by sonicviz** [comment]
How can you say that? It has to have some relationship to Base, otherwise it would work out of the box!

**Comment by themeteorchef** [comment]
Fibers is a part of Meteor but not a dependency of Base. Can you check the latest release (4.7.0) and see if this is fixed there? Also, some others have reported success using `meteor npm install` vs `npm install` to add deps. If neither of those work, feel free to reopen.

**Comment by sonicviz** [comment]
No Joy with "Meteor npm install" and latest versions of meteor and node 4.6


G:\Meteor Projects\Meteor 1.4\base-master>meteor
[[[[[ ~\G\Meteor Projects\Meteor 1.4\base-master ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Meteor 1.4.1.1 is available. Update this project with 'meteor update'.
W20160905-11:23:38.069(9)? (STDERR) G:\Meteor Projects\Meteor 1.4\base-master\.meteor\local\build\programs\server\shell-server.js:15
W20160905-11:23:38.152(9)? (STDERR) require("meteor-promise").makeCompatible(Promise, require("fibers"));
W20160905-11:23:38.153(9)? (STDERR)                           ^
W20160905-11:23:38.155(9)? (STDERR)
W20160905-11:23:38.157(9)? (STDERR) TypeError: require(...).makeCompatible is not a function
W20160905-11:23:38.160(9)? (STDERR)     at Object.<anonymous> (G:\Meteor Projects\Meteor 1.4\base-master\.meteor\local\build\programs\server\shell-server.js:15:27)
W20160905-11:23:38.161(9)? (STDERR)     at Module._compile (module.js:409:26)
W20160905-11:23:38.164(9)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20160905-11:23:38.166(9)? (STDERR)     at Module.load (module.js:343:32)
W20160905-11:23:38.167(9)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160905-11:23:38.170(9)? (STDERR)     at Module.require (module.js:353:17)
W20160905-11:23:38.171(9)? (STDERR)     at require (internal/module.js:12:17)
W20160905-11:23:38.173(9)? (STDERR)     at Object.<anonymous> (G:\Meteor Projects\Meteor 1.4\base-master\.meteor\local\build\programs\server\boot.js:101:3)
W20160905-11:23:38.184(9)? (STDERR)     at Module._compile (module.js:409:26)
W20160905-11:23:38.186(9)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
Terminate batch job (Y/N)?
^C
G:\Meteor Projects\Meteor 1.4\base-master>

**Comment by sonicviz** [comment]
Scratch that!. Finally got Base 4.7 working.

I had to do a meteor update --all-packages and it finally worked.

Must have been a package conflict?
