### ISSUE TITLE
bootstrap.js

### ISSUE THREAD

**Issue by HatemJerbi** [themeteorchef/base#170]
why importing bootstrap.js?

React-Bootsrap official Docs:
        React-Bootstrap is a complete re-implementation of the Bootstrap components using React. It has no dependency on either bootstrap.js or jQuery. If you have React setup and React-Bootstrap installed you have everything you need.
You can consume the library as CommonJS modules, ES6 modules via Babel, AMD, or as a global JS script.

**Comment by themeteorchef** [comment]
It looks like this has changed/was an oversight. Going to flag this as a refactor.
