### ISSUE TITLE
static-html vs. blaze-html-templates

### ISSUE THREAD

**Issue by acomito** [themeteorchef/base#171]
Is there anything to worry about when using `blaze-html-templates` instead of `static-html`?

I'm trying to do some blaze-inside-react stuff and I can't seem to get it down without `blaze-html-templates` and I can't seem to have both `blaze-html-templates` and `static-html` installed.

**Comment by themeteorchef** [comment]
Nope! Should be okay to live side-by-side. Static HTML just adds the ability to render your basic html file (`/client/main.html`) but without all of the Blaze stuff. The `blaze-html-templates` package should cover you if you drop `static-html`. If it doesn't, let me know so I can add some docs :)
