### ISSUE TITLE
Bootstrap package

### ISSUE THREAD

**Issue by Tataro** [themeteorchef/base#185]
<img width="677" alt="screen shot 2559-09-14 at 3 31 14 pm" src="https://cloud.githubusercontent.com/assets/5748363/18505182/522e57c6-7a90-11e6-868d-4b497f581095.png">
Hi,
I am new to front-end skill, as you can see the page include 'bootstrap' after include 'merged-stylesheets.css', so if i modify bootstrap style ( e.g. body { background-color: black; } ), it won't work. how can i fix this problem?

**Comment by themeteorchef** [comment]
@Tataro your approach is best if you'd like to circumvent this at the moment.
