### ISSUE TITLE
Retrieve or wait for user subscription in react-router

### ISSUE THREAD

**Issue by dinhtungdu** [themeteorchef/base#189]
Hi!

First thank you for the base, so sweet!

Second, question: How can I wait for user subscription in react-router? Currently, I have a function `requireAdmin` and pass it to `onEnter` to check if user is admin or not, it needs `Meteor.user()` but when I go to admin panel directly by url (or refreshing the admin page), `Meteor.user()` always return `undefined`.

I searched for this issue and I got that happens because the user subscription didn't ready at that time. I found some solution but they only apply for iron/flow router, not react-router. 

Do anyone have a workaround on this. Any help is very appriciated! 💯

**Comment by arthurkirsz** [comment]
Hi @dinhtungdu 

I wanted to do the same thing and ended up creating a Container to wrap my Admin views. 

Here is a link to a gist if you want to see how it looks : https://gist.github.com/arthurkirsz/0c123cc4af34b74de076021967f68a36

If you come up with another solution or some enhancement to mine, please share it with me :p !

**Comment by nialexsan** [comment]
Hi @dinhtungdu! 
I would like to suggest creating two different apps for your site and admin panel bound to one DB. This architecture facilitates access control and allows to customize easily URL for admin panel.

**Comment by themeteorchef** [comment]
Hey folks, going to close this out but feel free to keep sharing stuff here if need be :)
