### ISSUE TITLE
large static assets

### ISSUE THREAD

**Issue by kinger-de** [themeteorchef/base#190]
Hi@all.

I'm trying to serve a large static video file to an react component.

I don't know the right place where to save the video file.
If i put the file under /public or /private meteor crashes with RangeError in buffer.js:25.
So i put the file in /data (tried also /imports/assets). It seems like meteor can handle this and don't crash.
But i don't know how to load this file in my react component. Tried to use absolute paths like /data/foo/bar.mp4, but the video won't be loaded. (I think, meteor tried to load this file through the router and answered with an 404 error)

Is there an Best Practice or similar to serve large static asset files or can somebody give me an hint?

thanks & greetings

**Comment by themeteorchef** [comment]
Hi there. For large static assets—any static asset, really—it's wise to use something like Amazon S3 instead of storing stuff locally.

**Comment by kinger-de** [comment]
Thank you for your reply.

Yes, you are right. Something like Amazon S3 is the best way to store assets. But this won't work if the user is offline, right? How i can handle this, if the large asset is an part of the layout and i want show it if the user is offline too?

Should i use something like AppCache?

**Comment by themeteorchef** [comment]
This is best stored in your `/public` directory in the root of your project. In your code, then, you can access a file at `/public/example.mp4` like `<a href="/example.mp4">Example Movie</a>`. The punchline is that Meteor serves anything in your `/public` directory off the root domain like `http://localhost:3000/example.mp4`.
