### ISSUE TITLE
Errors when running meteor or meteor npm start on fresh install

### ISSUE THREAD

**Issue by amazingBastard** [themeteorchef/base#191]
I get these errors when trying to run a clean install of base:

/Users/username/.meteor/packages/meteor-tool/.1.4.1_1.danfol++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/05/0wkvrfp12dz04mdmyn18j9jh0000gn/T/mt-hd2bz1/os.json'
    at Error (native)

Not sure if this was reported or not. Any idea what I'm missing? Thanks.

**Comment by jasenkoh** [comment]
running `meteor` command for second time helped me (I already have 1.4.1.2 installed on my local so it might be version conflict)

**Comment by themeteorchef** [comment]
Base is on my back burner while I get the new TMC site wrapped up but I will take a look at this when I do Base upgrades next!

**Comment by themeteorchef** [comment]
Going to close this out as it looks like it's been fixed in the upcoming 4.8.0 release. If not, please reopen :)
