### ISSUE TITLE
How to styles components?

### ISSUE THREAD

**Issue by GilbertMizrahi** [themeteorchef/base#194]
I have worked with Bootstrap before, but I ma trying to use base and I don't get how to style components.

No matter what I do , the styles predefined by 'bootstrap/dist/css/bootstrap.min.css'; are the ones applied.
Also, where I am supposed to add my custom styles. it seems I should include them in the client.stylesheets directory, but I need to see an example.

Anyone has an example of an app customizing styles?
Finally, how I will use a theme from third parties?

**Comment by themeteorchef** [comment]
Hey @GilbertMizrahi :) 

For custom styles, yes, they'll need to be placed in the `/client/stylesheets` directory. As far as an example goes, the recent [React Sticky Scroll](https://github.com/themeteorchef/react-sticky-scroll/tree/master/client/stylesheets) tutorial includes some custom CSS. If you look at that `/client/stylesheets` directory, the `_sticky.scss` file shows off some CSS and is imported into the app via the `/client/stylesheets/application.scss` file.

I'm going to close this for now but feel free to keep posting questions!
