### ISSUE TITLE
Component State and Promises

### ISSUE THREAD

**Issue by appjitsu** [themeteorchef/base#197]
https://github.com/themeteorchef/base/blob/b5a0782e64e36518d85444e555afc8b543fe3f2d/imports/ui/pages/ViewDocument.js

Ok so in the above code there is an onClick handler. Let's say you have a long-running process in a server side method that returns a promise. When the promise is done, I need to update the state of the component. Then dependent on that state, I need to show a div. How would I handle this?

**Comment by themeteorchef** [comment]
Howdy :) Take a peek at this tutorial: https://themeteorchef.com/snippets/promise-based-modules/.

The basic premise is that you'll want to have your method calling and returning a Promise-based function. That way, when you resolve your promise, the response will be pushed down to the client (via the method callback) and you can do any work you need to there. Using the example above, you'd set your state [on this line](https://github.com/themeteorchef/base/blob/b5a0782e64e36518d85444e555afc8b543fe3f2d/imports/ui/pages/ViewDocument.js#L13).

**Comment by appjitsu** [comment]
OK Thanks I'll give that a shot.
