### ISSUE TITLE
Getting Started with Base Tutorial

### ISSUE THREAD

**Issue by rojerian** [themeteorchef/base#204]
First of all ... Base is a great initiative and certainly helped get me started.  However, it doesn't expose the wisdom that went into its clearly quite thoughtful design.  I think further documentation shall be of value to both Base and Meteor adoption.

An initial step could be to add a few lines of documentation to each file explaining: 

- why it exists ( purpose ), 
- its relationship to other files in the distribution,
- a few words about key methods, components and packages within,
– and some comments about adding or subtracting these items to construct a richer application.

Afterwards, the chef could pen a few recipes in a cookbook to describe specific and common application engineering objectives that touch multiple files in the boilerplate.  Recipes such as: adding an authorisation edit page, extending a more complex data schema and building brand-new components, come to mind.

I be pleased to contribute to this useful work but as you can sense I am not yet qualified.

**Comment by benjaminwil** [comment]
Hey, this is Benjamin (who works on The Meteor Chef). Thanks @rojerian for opening this issue. We're hoping to revamp the Base documentation _and_ do a classic The Meteor Chef-style tutorial as an introduction to Base.

If you (and anyone else) could post questions that you'd like to see addressed in the Base —_or_ in a tutorial format, this would be immensely helpful to @themeteorchef and I.

**Comment by themeteorchef** [comment]
@rojerian done! Post here: https://themeteorchef.com/blog/getting-started-with-base-v4-x

Open to ideas for how to expand this in the future, too.
