### ISSUE TITLE
React Bootstrap ListGroupItem and Button component hrefs are resulting in page loads.

### ISSUE THREAD

**Issue by PaulSavignano** [themeteorchef/base#205]
The hrefs on React Bootstrap's ListGroupItem and Button components are currently resulting in page loads.  Suggest a refactor to Link for Buttons and browserHistory.push() for ListGroupItems.

**Comment by manacim** [comment]
Any update on this? I'm new to meteor and everything about this boilerplate.

**Comment by PaulSavignano** [comment]
Hi Cim,
I submitted a pull request to correct the behavior.  Each ListGroupItem
needs an onClick handler pointing to a function that uses
browserHistory.push() and the hrefs removed.  The Buttons can be wrapped in
a Link element from React Router.


Paul
(760) 390-3534

**Comment by manacim** [comment]
Thanks for the update! I added your code to the plate and it works like it should.

**Comment by PaulSavignano** [comment]
Good to hear!

**Comment by 416serg** [comment]
or [React Router Bootstrap](https://github.com/react-bootstrap/react-router-bootstrap) can be implemented :)

**Comment by themeteorchef** [comment]
Going to close this out as this is being merged in the next release :)
