### ISSUE TITLE
Blaze structure

### ISSUE THREAD

**Issue by jdnichollsc** [themeteorchef/base#207]
Hi guys,

Can I use this structure with **Blaze**? Exist any example?

Thanks for all, Nicholls

**Comment by themeteorchef** [comment]
Hey Nicholls, yep! It's React by default but Blaze code should run just fine within it. Take a peek at the [pre-4.0 release](https://github.com/themeteorchef/base/tree/v3.4.0) to see how we used to work with Blaze.

**Comment by jdnichollsc** [comment]
Thanks for the example! Check my Meteor Structure with Blaze! https://github.com/jdnichollsc/Meteor-Starter-Template
