### ISSUE TITLE
Bootstrap CSS and stylisheets scsss

### ISSUE THREAD

**Issue by anthonyferreol** [themeteorchef/base#212]
Hey,

I'm having a little issue about bootstrap and overriding their css. 
Creating our own class and modifying them in a scsss in client/stylesheets does not override the css of bootstrap, since bootstrap is loaded last. 
To modify the basic style, we will have to add !important in every property ... 

Any idea how to modify the boilerplate properly to make sure our own css is used last ?

**Comment by rglover** [comment]
Hi, @anthonyferreol. You will want to load your CSS using the `application.scss` file, making sure that any imported files are prefixed with an underscore like this: `_myComponent.scss`. 

Can you share a screenshot of your file structure? May be able to figure out why the loading isn't working.

**Comment by anthonyferreol** [comment]
Hi, @rglover. My css is loading, sorry if I wasn't clear enough, but my problem is about the fact that bootstrap css load AFTER my css. Making my own css obsolete, unless I use the !important.

I found this https://github.com/themeteorchef/base/issues/185 that do the job !
