### ISSUE TITLE
Trouble with npm scripts

### ISSUE THREAD

**Issue by acomito** [themeteorchef/base#213]
My meteor npm deploy script never runs. It always says:

```
Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview
```

my script is:

`DEPLOY_HOSTNAME=galaxy.meteor.com meteor deploy --settings settings-development.json http://dev.meteorapp.com --owner dev`

This works if I paste it into the terminal, but it never automatically runs from the script command... do these need to be registered somehow for them to work?

`meteor npm start `works as expected... just not meteor npm staging or meteor npm production

lastly, congrats of TMC V3 it looks awesome

**Comment by themeteorchef** [comment]
Howdy! For scripts other than start you'll want to run these with `npm run <script>`, so `npm run production`, for example.

Thanks for your thoughts on the site :)
