### ISSUE TITLE
Warning: Failed prop type: Required prop `doc` was not specified in `ViewDocument`

### ISSUE THREAD

**Issue by chip** [themeteorchef/base#223]
The error above shows up in the browser console immediately after removing a document.

![themeteorchef-base-delete-issue](https://cloud.githubusercontent.com/assets/31725/22273439/5ce4c13a-e266-11e6-84f0-e81d95b9f1ec.png)

I've pulled from master and HEAD is currently `1841eddb5cbb30336cdf085c8f0d5cdcb63d7278 Merge branch 'chore/bump_meteor_#198'`

**Comment by chip** [comment]
I'm not sure what's happening, but would be happy to submit a fix if someone can point me in the right direction. Thanks.

**Comment by chip** [comment]
Actually, I wasn't at the latest commit when I originally posted. Now I'm at `cc7aef11fd1bc182b42178d704f8213b7d224a45 bump base version in README.md and index component` and the problem persists, so I'm reopening.

**Comment by themeteorchef** [comment]
Can confirm, thanks for reporting @chip. Flagging as a bug.
