### ISSUE TITLE
Could you explain why use "react-komposer" instead of "react-meteor-data"?

### ISSUE THREAD

**Issue by thearabbit** [themeteorchef/base#231]
Could you explain why use "react-komposer" instead of "react-meteor-data"?'

**Comment by thearabbit** [comment]
Why don't use the last version of `react-komposer`.

**Comment by themeteorchef** [comment]
@thearabbit `react-komposer` is used because it allows us to pass configuration options to React (needed because it fixed a bug in React Bootstrap).

The latest version of `react-komposer` came out recently and we haven't had a chance to update to it yet.

**Comment by thearabbit** [comment]
Thanks I will to learn `react-komposer`.
