### ISSUE TITLE
Glyphicon don't work

### ISSUE THREAD

**Issue by thearabbit** [themeteorchef/base#241]
I tried to use `Glyphicon`, but don't work
```js
import {Glyphicon, Button} from 'react-bootstrap';

<Glyphicon glyph="star" />
// or              
<i className="glyphicon glyphicon-remove form-control-feedback"></i>
```
How to solve?

**Comment by themeteorchef** [comment]
No stylesheet/icon files for Glyphicon are loaded into Base, so you'll likely need to pull these in separately in order for this to work.

**Comment by thearabbit** [comment]
OK, now it work fine, after I copy `fonts folder -> /public`.
