### ISSUE TITLE
Q - Is it possible to use bootstrap themes with Base?

### ISSUE THREAD

**Issue by jenlikescode** [themeteorchef/base#255]
Has anyone successfully integrated a bootstrap admin theme within Base? Something like "SB Admin 2" or "INSPINIA - Responsive Admin Theme".

https://startbootstrap.com/template-overviews/sb-admin-2/ 
https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S

It seems as though there will be some non-trivial decoupling within each theme and wondering if it's even possible - as in, will things break when updating Base?

**Comment by themeteorchef** [comment]
@jenlikescode depends on the theme/how it works. If there are heavy modifications to the Bootstrap markup in the theme, then yes, it will likely break (the underlying `react-bootstrap` package is a 1:1 implementation of Bootstrap v3). 

That said, you can always rip out parts of the UI and replace them with custom markup/components if need be. Based on that link, it looks like you'll be on the hook for hand-coding a lot of the components in React.

**Comment by jenlikescode** [comment]
@themeteorchef Got it! Thank you for confirming!
