### ISSUE TITLE
Template Helpers

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#33]
A reader expressed an interest in having a few of the more generic UI helpers present in the recipes present in Base. Need to comb through to see _what_ would be a good candidate for this. May even be helpful to have as a package, too.

**Comment by flt123** [comment]
Some helpers are available at http://www.meteortuts.com/video/globalhelpers

**Comment by themeteorchef** [comment]
Cool! Thank you for sharing this @flt123. Definitely some good ones in there :)
