### ISSUE TITLE
README doesn't say how to load settings.json 

### ISSUE THREAD

**Issue by leoj3n** [themeteorchef/base#35]
`meteor --settings settings.json`

**Comment by themeteorchef** [comment]
@leoj3n this is a goof, thanks for pointing this out :)

**Comment by leoj3n** [comment]
Thanks to @ddaza for submitting this issue under my account (we were pair programming).

**Comment by themeteorchef** [comment]
@leoj3n just realized I didn't send over a heads up, this has been updated!

**Comment by leoj3n** [comment]
Got a notification when you closed via commit syntax, so no worries.
