### ISSUE TITLE
Flow Router

### ISSUE THREAD

**Issue by discdiver** [themeteorchef/base#54]
Feature request: Would be great to be able to easily use Flow Router with Base. Router Layer https://github.com/nicolaslopezj/meteor-router-layer/ helps package authors to support multiple routers.

**Comment by themeteorchef** [comment]
@discdiver thanks for sharing this, haven't seen it before!

I'm in the process of trying to convert to Flow Router now, but have gotten stuck on how best to handle authentication. I like the look of Router Layer, but my concern is trying to do too much at once (i.e. would it be better to just pick a solution and stick to it).

Despite its simplicity in most places, in some (like auth), Flow has added a bit more complexity/stuff to consider. If you have experience handling auth/have examples, let me know!

**Comment by discdiver** [comment]
Thanks, Chef. I hear what you're saying on simplicity. Just seems like
everything is moving to Flow Router. As you mentioned, it's what the core
team seems to be giving the nod to, the vast majority of devs seem to
prefer it due to it's clarity and simplicity, ability to use it with React
and Angular, and problems with iron:router behaving unpredictably and
iron:router seems to have had a lull in its maintenance.

I am pretty newby to all this, but trying to set things up the best way
possible and anticipate the future a bit. I'm persuaded to throw my lot in
with Flow Router.

Here's an article on Authentication I just found a minute ago, while
searching for the link to a medium article in the comments to your flow
router snippet that I didn't see in the article or comments - might have
just missed it. haven't even checked out this article yet, but sounds on
topic for your concern.
https://medium.com/@satyavh/using-flow-router-for-authentication-ba7bb2644f42
<https://medium.com/@satyavh/using-flow-router-for-authentication-ba7bb2644f42>

Love you tutorials. The in-depth explanations are great. FYI, my main
question as I'm going through the ones with iron router is, "What do I need
to change to get this to work with flow router."

Have a great day,
Jeff

**Comment by themeteorchef** [comment]
Thanks, Jeff! I'll take a look at those links. 

You're right, everything does seem to be moving that way. As much as I can, though, I want to ensure the simplest possible solution is used. For example, if it takes me a long time to explain how a feature works in something like documentation, there's a problem. In contrast, in Iron Router, the hooks feature is implemented in a way that's complementary to checking authentication status at the router level, so the problem doesn't arise there (though, that's not to say IR is the 100% desired solution moving forward).

On all fronts save for authentication, Flow Router is excellent. I understand that the decoupling of things like reactivity from the router is important, but the cost that's incurred by developers to build less-than-favorable solutions in service of that is a tricky one to navigate around.

I hear you, though! Will keep this open and post updates as I learn more/make progress :)

Feel free to post snippets/pull requests as you get stuff working too.

**Comment by discdiver** [comment]
cool. will do.

I just read the meteor article I sent over and they make authentication
with flow router look easy.

Thanks again,
Jeff

**Comment by discdiver** [comment]
Following up on flow routing permissions:

Not sure you want to go this way because it creates more dependencies on
external packages, but it does seem to simplify authorization with flow
router and it's a super popular package:
https://github.com/alanning/meteor-roles/tree/1f0dcf4d928dc735ffe0ab6dd2447364adf685ea#user-content-usage

Have a good weekend,
Jeff

**Comment by themeteorchef** [comment]
Not against adding something like this, but like you've said, you're adding additional dependencies to fix a problem elsewhere. I've considered adding roles for other reasons, though, so may be a nice overlap with some other features.

**Comment by themeteorchef** [comment]
Notes:

- Make sure to grab reset token using Flow's router params.

**Comment by l0oky** [comment]
What has happened with flow router? It seems that we use react router now?
