### ISSUE TITLE
Add package aldeed/simple-schema

### ISSUE THREAD

**Issue by Narven** [themeteorchef/base#72]
Adding the package [https://atmospherejs.com/aldeed/simple-schema](https://atmospherejs.com/aldeed/simple-schema) would be an awesome fit together with existing collection2

for validation

**Comment by themeteorchef** [comment]
@Narven this should be automatically pulled in by collection2 as it depends on simple-schema. Is that not the case?

**Comment by Narven** [comment]
@themeteorchef Yes thats completely correct. Sorry about that, never notice. I always add them separated.

**Comment by themeteorchef** [comment]
No worries :)
