### ISSUE TITLE
Improvement using eslint

### ISSUE THREAD

**Issue by jptissot** [themeteorchef/base#75]
Hey, I just started using your template and it's a great starting point. I've been doing some research on Meteor and was about to create an application using most of the packages of this base. You just saved me a lot of time, thanks :+1: 

One cool thing to add to the base would be a `.eslintrc` file. I've just setup this base with eslint support following this guide (http://info.meteor.com/blog/set-up-sublime-text-for-meteor-es6-es2015-and-jsx-syntax-and-linting). The base does not adhere to all guidelines in that configuration file but it would be fairly easy to modify it for your needs. 

Thanks again for this.

**Comment by themeteorchef** [comment]
Hey @jptissot! 

I'm using JSHint on my end now (with a `.jshintrc` in the root). What is the difference between that and ESLint? If they're similar I'm not against switching out if ESLint provides more functionality/is more inline with MDG's solution.

**Comment by jptissot** [comment]
They're very similar tools. I just personally like eslint for it's configurability. It really comes down to a preference I believe. This article sums up it's benifits : https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48

**Comment by themeteorchef** [comment]
Cool, I'll take a peek! Thanks for sharing. Will keep this open for now.

**Comment by arvi** [comment]
Hello :) I created a pull request for this: https://github.com/themeteorchef/base/pull/82
