### ISSUE TITLE
Meteor update indirect dependency cosmos:browserify 0.5.1

### ISSUE THREAD

**Issue by paul-bo** [themeteorchef/base#76]
Maybe it's a stupid question. But when I run meteor update I get a notification:
```
Newer versions of the following indirect dependencies are available:
 * cosmos:browserify 0.5.1 (0.8.0 is available)
To update one or more of these packages, pass their names to `meteor update`.
```

I don't know from where the dependency is coming. After checking the github page of browserify it says that it needs 0.8.0 to work with meteor 1.2
Is it okay to simply run the update? And is this something that this repo need an update for?

**Comment by themeteorchef** [comment]
@paul-bo I believe this is a dependency of Flow Router. Strange that you're getting an error (MDG may have added this alert recently). See [this line in Flow Router's package.js](https://github.com/kadirahq/flow-router/blob/master/package.js#L63). It looks like they're pinned to `0.5.0`.

If you're feeling adventurous, I can't imagine an upgrade hurting too bad :)

**Comment by paul-bo** [comment]
I have updated browserify. Everything went fine.

**Comment by themeteorchef** [comment]
Cool, sounds good!
