### ISSUE TITLE
Base extensions as microservices

### ISSUE THREAD

**Issue by josephdburdick** [themeteorchef/base#86]
Hey @rglover what are your thoughts on things like the invitations feature being hot-swappable because it's coded as a microservice? This way you could add or remove the functionality without much hassle.

**Comment by themeteorchef** [comment]
This make sense to me. Something I thought about recently was starting a pattern like `themeteorchef:base-<service>` where `<service>` equals the name of some microservice that can be added or removed at will. When you say invitations, are you referring to something that's been posted on the site/

**Comment by josephdburdick** [comment]
Yes @rglover I'm speaking specifically in context about your post regarding building a user admin.

**Comment by themeteorchef** [comment]
Ah, gotcha. All about this! Would be cool to have `themeteorchef:base-invite` or something similar. Interested in working on it (can help, too)?

**Comment by josephdburdick** [comment]
I would prefer to add stuff to Base this way because it follows best practices to creating scalable code so I'll look into it – I've never done it before.

**Comment by themeteorchef** [comment]
Okay cool. Keep me updated on this. Definitely want to start doing this.

**Comment by zeroasterisk** [comment]
+1 on splitting into packages/modules --- not only is this a great pattern for how we "should be doing it" but a great resource for developers trying to figure out how to do things like this.
