### ISSUE TITLE
Fix environment vars breaking on startup with `meteor`

### ISSUE THREAD

**Issue by josephdburdick** [themeteorchef/base#91]
@rglover line 2 of `server/modules/set-environment-variables.js` causes `$ meteor` command to break because without --settings the `Meteor.settings.private` object you're declaring to doesn't exist. You must wrap the environmental variable declarations in a conditional statement detecting the private settings object so Meteor doesn't :hankey: the bed.

**Comment by josephdburdick** [comment]
Fix visible [here in my original PR](https://github.com/josephdburdick/base/blob/addEnvironmentVariables/server/modules/setEnvironmentVariables.js#L2).

**Comment by themeteorchef** [comment]
Ah, didn't realize that's what this was for! Will add a patch.

**Comment by widespaceDLS** [comment]
that is happening over at ~ building-a-user-admin ~ too.  Different code point, different semantics. I'm opening an issue for it.

**Comment by josephdburdick** [comment]
@widespaceDLS Until this issue is patched with the conditional necessary, a surefire way to bypass it is to run `npm start` instead of `meteor`.

**Comment by widespaceDLS** [comment]
I'm new to meteor and javascript web development. Where would I look to understand how to use that? I quickly found out it is a node tool. It looked like I would need to install node, then of course spend some time learning that.  Or is it as simple as installing node and then use the npm shell to run the meteor project?

**Comment by themeteorchef** [comment]
@widespaceDLS I wrote a little bit on this in a snippet that you can [check out here](https://themeteorchef.com/snippets/making-use-of-settings-json/#tmc-automating-settingsjson). That will walk you through how npm scripts are utilized in Base. 

Re: getting access to these, they only require an installation of Node, which, you should have already if you're running Meteor okay (npm is bundled with this, too). These are nothing more than a shorthand method for starting Meteor with multiple options. Take a peek at [this page](https://themeteorchef.com/base/npm-scripts/) in the Base docs to get a more contextual example.
