### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by c316** [themeteorchef/base#92]
Just a suggestion, but it would be great to include logging.

Package: wylio:winston-papertrail

Folder: Server
File: papertrail.js

```
//creating a global server logger
logger = Winston;

logger.add(Winston_Papertrail, {
	levels: {
			debug: 0,
			info: 1,
			warn: 2,
			error: 3,
			auth: 4
		},
		colors: {
			debug: 'blue',
			info: 'green',
			warn: 'red',
			error: 'red',
			auth: 'red'
		},

		host: "logs.papertrailapp.com",
		port: Meteor.settings.papertrail.port, //this will be change from the papertrail account to account
        handleExceptions: true,
        json: true,
        colorize: true,
		logFormat: function(level, message) {
		return '[' + level + '] ' + message;
  }
});
logger.info(" =====> Meteor App restarted "+ new Date( Date.now()) +" <=====");

// Now add the server method used to get logging
// from the client to the server so it can be sent out

Meteor.methods( {
    // This method is used on the client side to send logs to papertrailapp.com
    clientLog: function ( message ) {
      check(message, String);
      logger.info( "client-side-log ", message );
    }
  }
);
```

For the client side of this instead of calling ```console.log``` setup a custom function

```
// First
//on client side
logger ={}

// then wrap the Meteor call to make it easier to call for logging client side
logger.log = function (message) {
  Meteor.call('clientLog', message);
}
```

Anyone who uses this will first need a papertrailapp.com account, but they are free with two days of searchable logs and 7 days of archived logs. I found papertrailapp.com to be much more user friendly then loggly.com. Although I did use an article I found at loggly.com to get the client side logging working. 

https://www.loggly.com/blog/managing-a-meteor-application-in-production-three-real-log-management-use-cases/

**Comment by themeteorchef** [comment]
Hey @c316 thanks for the suggestion :)

I would leave this out of Base because it's pretty specific to the user's project (i.e. everyone may not use logging, especially this specific service). If this is something you need, I would recommend setting up a fork of Base and adding this as necessary.
