### ISSUE TITLE
Add /methods to /both and /server

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#98]
Anecdotal based on myself and questions from other devs, but there's been a lot of confusion/frustration around having the methods directory in `/both`. Because it's run on both the client and the server, some server-only code throws a fit. The solution is to wrap server specific code in an `if ( Meteor.isServer ) {}` check, but this always introduced more headaches. 

Moving this back to the server will keep functionality intact and remove the `isServer` checks.

**Comment by josephdburdick** [comment]
Hi Ryan. Will this remove optimistic UI?

**Comment by themeteorchef** [comment]
Yes. One option (this will need to be documented) is to define methods where latency compensation/optimistic UI is preferred in `/both`, with the knowledge that server-only code will need to be wrapped. I'm finding that it's not an all or nothing situation; sometimes you _do_ want it and other times it's not really necessary (or a chore).

**Comment by themeteorchef** [comment]
The ideal solution here is to have `/methods` added to each of the contexts: `/both` and `/server`. If you have a method that needs latency comp, stash it in `/both/methods`. If it needs to be server only, just stash it in `/server/methods`. Same sub-patterns (per-type, i.e., insert, update, etc) apply inside of the respective `/methods` directories.
