### ISSUE TITLE
Investigate using Validator.js for validation instead of jQuery

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/base#99]
This would parlay into a move to React later. Need to play with this but seems like it may be a solid option: https://github.com/chriso/validator.js.

**Comment by jamiedumont** [comment]
Are you planning a move to React for base? We've been using it with our first, tentative steps into a Meteor project, and have been looking at React wondering whether to make the jump. We'll also be booking some Chef's Table slots in the New Year.

**Comment by themeteorchef** [comment]
Hey @jamiedumont I am! I need to book out some time to do the initial conversion (keep an eye on the `base-react` branch here) but it's on my list. 

Sounds good re: Chef's Table!

**Comment by jamiedumont** [comment]
@themeteorchef Excellent! Is this a personal preference or a sign of Meteor maturing towards widely used tools?

**Comment by themeteorchef** [comment]
Hmm, a little bit of both. More of an acknowledgement of Meteor starting to adapt different tech and if I'm going to teach it properly I need all of my tools well-aligned (e.g. it's a pain in the butt to refactor from Blaze to React for every React-based recipe).
